### ISSUE TITLE
Intro to Pandas, Exercise 2

### ISSUE THREAD

**Issue by Jiaxigu** [nathanquinteiro/ADA-Homework#2]
In _Intro to Pandas - Exercise 2_, your solution writes:

`data[[name.endswith('bacteria') for name in data.phylum] and [value > 1000 for value in data.value]]`

However, `and` actually doesn't work here. If you change 1000 to 100, the code returns:
![2016-10-06 11 23 23](https://cloud.githubusercontent.com/assets/14288948/19147211/6395a32e-8bb7-11e6-9421-cfe6e27eb035.png)

Only the second argument is processed. Here I think `&` works well. My personal suggestion would be:

`data[[name.endswith('bacteria') for name in data.phylum] & (data.value > 1000).values]`

Reference: [stackoverflow](http://stackoverflow.com/a/13616382)

Best regards,
Jiaxi

**Comment by lseguy** [comment]
I am reviewing your assignment and was going to say the same thing. I also think @Jiaxigu's suggestion is the best one.

You can even improve it a bit, avoiding Python's list comprehension:
`data[data.phylum.str.endswith('bacteria') & (data.value > 1000)]`

Best,
Louis
